/// <reference types="vite/client" />

/** The brand pack's colour tokens as CSS, generated by src/brand/brandColoursPlugin.ts. */
declare module 'virtual:brand-colours.css';

interface ImportMetaEnv {
  /** Dev server only; see src/auth/tokenStore.ts. Never set in CI or a deploy. */
  readonly VITE_DEV_TOKEN?: string;
}

/** Package version and short commit, injected at build time (vite.config.ts); shown in Settings → About. */
declare const __BUILD_VERSION__: string;
